### PR TITLE
require Time::HiRes in t/900_bugs/041_cachedir_other_process.t

### PR DESCRIPTION
**Pull request by bayashi**

### CODE REVIEW

**Comment by syohex** [comment]
Is this really necessary ? Because `Time::HiRes` is standard package since `v5.7.3` and Text::Xslate supports only 5.8 or higher versions.

**Comment by bayashi** [comment]
In deed, but I got a fail report without Time::HiRes.
It seems a problem of my environment only.
I'll investigate my case again.

**Comment by syohex** [comment]
Did you use CentOS(or Redhat distributions) ?

**Comment by bayashi** [comment]
Yes, I use CentOS.
And I resolved this problem to install perl-core package by yum.

**Comment by bayashi** [comment]
Thank you.

**Pull request closed without merging**
