### PR TITLE
fix #135

### LINKED ISSUE #135: Constants from lexical variables potentially modified elsewhere are deprecated
perl 5.21.7 has a new warning which is causing the test suite to fail. See http://www.cpantesters.org/cpan/report/57d24bca-88c4-11e4-b194-8c305ef060ad for a sample fail report.

### PR DESCRIPTION
**Pull request by eserte**

### CODE REVIEW

**Comment by miyagawa** [comment]
This is a meaningless change on the code level to just bypass the warnings - in which case it should better just turn off that specific warning with `no warnings`.

**Comment by kazuho** [comment]
Under the premise that we should create a constant in this case, IMO the suggested way is to apply the proposed PR, since that is the way suggested in the perldelta. 

> This usage is now deprecated in those cases where the variable could be modified elsewhere. Perl detects those cases and emits a deprecation warning. Such code will likely change in the future and stop producing a constant.
http://search.cpan.org/~bingos/perl-5.21.6/pod/perldelta.pod#Inlining_of_sub_%28%29_{_%24var_}_with_observable_side-effects

**Comment by miyagawa** [comment]
It's a fairly annoying change on the p5p side IMO, but I agree @kazuho that this is the only going forward (or make the directory lookup another sub so that `my $cache_dir` can be initialized in one shot)

However per my discussion with @gfx on twitter, a better fix would be to make the default cache dir location a global variable rather than a constant, since calculating this on a compile time doesn't give any performance benefit such as constant folding.

**Comment by gfx** [comment]
In this case, as @miyagawa said, I have found better way to avoid this issue (#138), and I'll release a new version today. 

IMO this perl's update is useful to write correct code as long as it detects really suspicious one. The problem is that the feature seems still incubating and finds right code as wrong one. It sucks.

**Comment by eserte** [comment]
@miyagawa: re "meaningless change" --- I think you're wrong here. If the constant was to be retained, then my proposed change is the only way to achieve this. And more or less this is also proposed in perldiag.pod (just try `perl -Mdiagnostics ...` on that code). `no warnings` would only help in this perl version, but this construct could be a fatal error in a future one.

**Comment by miyagawa** [comment]
@eserte i already stated that in the above message.

**Pull request closed without merging**
