### PR TITLE
Avoid generating malformed UTF-8 and replacement characters by inter…

### PR DESCRIPTION
**Pull request by pepl**
…polating the variable as-is if it is not a valid UTF-8 sequence (nc), Github issue #88

### CODE REVIEW

**Comment by syohex** [comment]
Thanks PR. However tests are failed on Perl 5.20 or higher versions.

**Comment by pepl** [comment]
Looks like with Perl 5.20 and higher the semantics of one-byte hex notated characters changed. Now covering that with the tests

**Comment by pepl** [comment]
Nicholas Clark provided an improved version of the patch. Travis CI checks pass.

**Comment by syohex** [comment]
Could you squash commits ?

**Comment by pepl** [comment]
Squashed

**Comment by syohex** [comment]
@pepl Thanks great work. I have cherry-picked your commit. :+1:

**Pull request closed without merging**
